#!/usr/bin/env bash
# Install Nginx
sudo apt-get update
sudo apt-get install -y nginx

# Ignore SC2154 for shellcheck
# shellcheck disable=SC2154

# Set the custom HTTP response header for Nginx
sudo sed -i '/server_name _;/a \\tadd_header X-Served-By $HOSTNAME;' /etc/nginx/sites-available/default

# Restart Nginx to apply changes
sudo systemctl restart nginx
