#!/usr/bin/env bash
# Configures an Ubuntu server as follows:
#   - localhost resolves to 127.0.0.2
#   - facebook.com resolves to 8.8.8.8

cp /etc/hosts ~/hosts.new
echo "127.0.0.2		localhost" > ~/hosts.new
echo "8.8.8.8		facebook.com" >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts

cp /etc/hosts /etc/hosts.backup

sed -i 's/127\.0\.0\.1/127.0.0.2/g' /etc/hosts

sed -i 's/157\.240\.11\.35/8.8.8.8/g' etc/hosts

echo "IP address updated successfully."
