#!/usr/bin/env bash
# Configures an Nginx server to listen on port 80.
# removes the default Nginx configuration file
service apache2 start
rm /etc/nginx/sites-enabled/default
# Configure Nginx to listen on port 80 for all active IPv4 IPs
ln-s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
#restarts nginx
service nginx restart
